language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
cache: pip
# install libjpeg-dev for Pillow to handle JPEGs
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - libjpeg-dev
# command to install dependencies
install:
  - pip install -U tox-travis setuptools codecov
# command to run tests
script: tox
after_success:
    codecov --file .tox/cov-*.xml
notifications:
  irc:
    channels:
      - "chat.freenode.net#dosage"
    use_notice: true
    skip_join: true
