language: python
python:
  - "2.7"
  - "3.3"
# whitelist
branches:
  only:
    - master
# install libjpeg-dev for PIL to handle JPEGs
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libjpeg-dev
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install pytest-xdist --use-mirrors
# command to run tests
script: make test PYTESTOPTS="--tb=short -n10"
#notifications:
#  email: false
