os: linux
language: python
jobs:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
      env: "CC_TEST_REPORTER_ID=2a411f596959fc32f5d73f3ba7cef8cc4d5733299d742dbfc97fd6c190b9010c"
cache: pip
git:
  depth: false
dist: xenial
before_script:
  - "curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter"
  - "chmod +x cc-test-reporter"
  - "if [ -n \"$CC_TEST_REPORTER_ID\" ]; then ./cc-test-reporter before-build; fi"
# command to install dependencies
install:
  - pip install -U tox-travis setuptools codecov
# command to run tests
script: tox
after_success:
  - codecov --file .tox/reports/*/coverage.xml
  - "if [ -n \"$CC_TEST_REPORTER_ID\" ]; then ./cc-test-reporter format-coverage --prefix $PWD/.tox/*/lib/*/site-packages --input-type coverage.py .tox/cov-*.xml; fi"
  - "if [ -n \"$CC_TEST_REPORTER_ID\" ]; then ./cc-test-reporter upload-coverage; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#dosage"
    use_notice: true
    skip_join: true
# Push site to gh-pages branch
deploy:
  - provider: script
    skip_cleanup: true
    script: .github/deploy.sh
    on:
      branch: master
      python: 3.9
