language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
dist: xenial
# command to install dependencies
install:
  - pip install -U tox-travis setuptools codecov
# command to run tests
script: tox
after_success:
    codecov --file .tox/cov-*.xml
notifications:
  irc:
    channels:
      - "chat.freenode.net#dosage"
    use_notice: true
    skip_join: true
# Push site to gh-pages branch
deploy:
  - provider: script
    skip_cleanup: true
    script: .github/deploy.sh
    on:
      branch: master
      python: 3.8
